name: syhunt test
on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Executar an치lise de c칩digo com Syhunt
        shell: powershell
        run: Start-CodeScan -pfcond 'medium' -output 'report.pdf'
        continue-on-error: true

      - name: Upload do Relat칩rio Syhunt
        uses: actions/upload-artifact@v4
        with:
          name: syhunt-report
          path: report.pdf
          if-no-files-found: error
